[package]
name = "guto/glyder"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
signal = "sleitnick/signal@1.5.0"
comm = "sleitnick/comm@0.3.2"